### ISSUE TITLE
A proper DerivingVia language extension

### ISSUE THREAD

**Issue by RyanGlScott** [RyanGlScott/ghc#18]
Currently, one only needs to enable `DerivingStrategies` to use `via`, which will almost surely not pass muster if we turn this into a GHC proposal. As discussed in an earlier call, we should:

* [x] Create a new language extension called `DerivingVia`
* [x] Have `DerivingVia` imply `DerivingStrategies`
* [x] Require the use of `DerivingVia` to use `via`

@Icelandjack has made initial progress on this in #13.

**Comment by Icelandjack** [comment]
https://github.com/RyanGlScott/ghc/commit/35cb889a06a249646b6d932c35d72abecdd24ce6

**Comment by RyanGlScott** [comment]
Wonderful! Thanks, @Icelandjack!
