### ISSUE TITLE
Fails to parse produts

### ISSUE THREAD

**Issue by Icelandjack** [RyanGlScott/ghc#2]
Fails to parse products

```haskell
> newtype X a = X (a, a) deriving (Semigroup, Monoid) via (Product a, Sum a)
<interactive>:19:76: error: parse error on input ','
```

can be worked around by a second layer of parentheses or type synonyms

**Comment by RyanGlScott** [comment]
That ended up not being so bad! Fixed in 30bc3f24af5d74152b803fdd5d69fb87a4693b75.
