### ISSUE TITLE
Reports that unbound variable has kind Type

### ISSUE THREAD

**Issue by Icelandjack** [RyanGlScott/ghc#22]
```haskell
{-# Language DerivingVia #-}

import Control.Arrow
import Control.Category
import Data.Functor.Compose

newtype Foo a b = Foo (a -> b)
  deriving Category
    via fooo
```

this erroneously reports

```
/tmp/A.hs:8:12: error:
    • Cannot derive instance via ‘fooo’
        Class ‘Category’ expects an argument of kind ‘* -> * -> *’,
        but ‘fooo’ has kind ‘*’
    • In the newtype declaration for ‘Foo’
  |
8 |   deriving Category
  |            ^^^^^^^^
```

**Comment by RyanGlScott** [comment]
That's an interesting error.

I'll optimistically claim that adopting the approach in https://github.com/RyanGlScott/ghc/issues/3#issuecomment-351427688 will turn this into a proper out-of-scope variable error, but I'll keep this ticket open as a reminder to double-check this program when that time comes.

**Comment by RyanGlScott** [comment]
Fixed in https://github.com/RyanGlScott/ghc/pull/27.
