### ISSUE TITLE
Mess with context of derived instances

### ISSUE THREAD

**Issue by Icelandjack** [RyanGlScott/ghc#23]
```haskell
class Lattice a where
  sup   :: a -> a -> a
  (.>=) :: a -> a -> Bool
  (.>)  :: a -> a -> Bool

newtype WrapOrd a = WrappedOrd a deriving newtype (Eq, Ord)

instance Ord a => Lattice (WrapOrd a) where
  sup   = max
  (.>=) = (>=)
  (.>)  = (>)
```

we can derive 

```haskell
deriving via Int    instance                   Lattice Int
deriving via [a]    instance Ord a          => Lattice [a]
deriving via (a, b) instance (Ord a, Ord b) => Lattice (a, b)
```

but we probably want different constraints here, the final one can maybe be generated from `(Bifunctor p, Lattice a, Lattice b)` but what about `Ord a => Lattice [a]`?

We already know that `Ord a :- Lattice (WrapOrd a)` so is it possible or indeed desirable to figure out how to derive `Lattice a :- Lattice [a]`.

**Comment by RyanGlScott** [comment]
I don't think this directly pertains to a bug in the GHC implementation, so closing.
