### ISSUE TITLE
"Last argument of the instance must be a data or newtype application"

### ISSUE THREAD

**Issue by Icelandjack** [RyanGlScott/ghc#24]
```haskell
{-# Language DerivingVia, StandaloneDeriving #-}

import Control.Applicative

class Functor f => Additive f where
  zero :: Num a => f a
  (^+^) :: Num a => f a -> f a -> f a
  (^+^) = liftU2 (+)
  (^-^) :: Num a => f a -> f a -> f a
  x ^-^ y = x ^+^ fmap negate y
  liftU2 :: (a -> a -> a) -> f a -> f a -> f a

newtype WrapApplicative f a = WrappedApplicative (f a)
  deriving (Functor, Applicative) via f

instance Applicative f => Additive (WrapApplicative f) where
  zero   = pure 0
  liftU2 = liftA2

deriving via (WrapApplicative Maybe) instance Additive Maybe
deriving via (WrapApplicative (Either a)) instance Additive (Either a)
-- deriving via (WrapApplicative ((->) a)) instance Additive ((->) a)
```

commenting the last out causes it to fail

```
/tmp/B.hs:22:1: error:
    • Can't make a derived instance of
        ‘Additive ((->) a)’ with the via strategy:
        The last argument of the instance must be a data or newtype application
    • In the stand-alone deriving instance for ‘Additive ((->) a)’
   |
22 | deriving via (WrapApplicative ((->) a)) instance Additive ((->) a)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by Icelandjack** [comment]
Discovered while writing 15a907c

**Comment by RyanGlScott** [comment]
Ah, good find. Indeed, as you've discovered, GHC considers `(->)` to be neither data type or newtype, but rather in its own class of verboten "primitive" types, and disallows their use in standalone `deriving` wholesale. But this seems like too onerous of a restriction since, for instance, one could profitably combine `(->)` with `DeriveAnyClass` (and `DerivingVia`, as you've discovered).

This is something that will need to be patched upstream in GHC.

**Comment by RyanGlScott** [comment]
See https://ghc.haskell.org/trac/ghc/ticket/13154#comment:8 for the upstream issue.

**Comment by RyanGlScott** [comment]
https://ghc.haskell.org/trac/ghc/ticket/13154 has been fixed, so all that remains to be done is to rebase on top of the upstream GHC `master`. We might want to hold off on this until some other fixes have landed (notably, @Icelandjack's in-flight parser changes).

**Comment by RyanGlScott** [comment]
We've rebased on top of GHC HEAD, so this is fixed now.
